services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  app:
    build: .
    container_name: discord-squad-app
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    command: uvicorn bot.main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80" # We only need port 80 for HTTP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
