services:
  # The Discord Bot Service
  bot:
    build: .
    container_name: discord-event-bot
    restart: always
    env_file:
      - .env
    # Add a volume to mount the Google credentials file
    volumes:
      - ./google-credentials.json:/usr/src/app/google-credentials.json:ro
    depends_on:
      - db
    command: >
      sh -c "
        echo 'Waiting for PostgreSQL to be ready...' &&
        while ! nc -z db 5432; do   
          sleep 1
        done
        echo 'PostgreSQL is ready, starting bot.' &&
        python bot/bot.py
      "

  # The PostgreSQL Database Service
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
