version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-event-bot
    environment:
      - DISCORD_TOKEN=MTM4NjE3NTAxMDYxMTM5NjY4OA.G19YLr.l13sqKUDHRbClI_TqfzITEJgBy379rSv8npV2s
    restart: always
    volumes:
      - .:/app
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
