services:
  # The Discord Bot Service
  bot:
    build: .
    container_name: discord-squad-bot
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: python -m bot.bot
    networks: # Add service to the custom network
      - squad-net

  # The FastAPI Web App Service
  web:
    build: .
    container_name: discord-squad-web
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    # The port is no longer mapped to the host, as Nginx will handle all external traffic
    expose:
      - "8000"
    command: uvicorn bot.main:app --host 0.0.0.0 --port 8000
    networks: # Add service to the custom network
      - squad-net

  # The Nginx Proxy Service
  nginx:
    image: nginx:latest
    container_name: discord-squad-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    depends_on:
      - web
    networks: # Add service to the custom network
      - squad-net

  # The PostgreSQL Database Service
  db:
    image: postgres:14
    container_name: postgres-squad-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: # Add service to the custom network
      - squad-net

# Define the custom network
networks:
  squad-net:
    driver: bridge
